export const SET_ACTIVE_FOLDER = 'SET_ACTIVE_FOLDER';
export const SET_ACTIVE_EMAIL = 'SET_ACTIVE_EMAIL';
export const EMAIL_CHANGE_READ_STATUS = 'EMAIL_CHANGE_READ_STATUS';
export const EMAIL_DELETE = 'EMAIL_DELETE';
